def main():
    print("This program will find the sum of your numbers")
    n = int(input("Enter how many numbers are to be summed: "))
    total_sum= 0
    for i in range (n):
        num= int(input("Enter your number: "))
        total_sum= total_sum + num
    print("The total sum of your numbers is: ",total_sum)
main()
def main():
    print("This program will find the average of your numbers")
    n = int(input("Enter how many numbers you would like to have averaged: "))
    total_sum= 0
    for i in range (n):
        num= float(input("Enter your number: "))
        total_sum= total_sum + num
    print("The average of your numbers is: ",total_sum/n)
main()
from graphics import*
win=GraphWin()
point=Point(130,130)
point.draw(win)
c=Circle(Point(30,20),25)
c.setFill("blue")
c.setOutline("red")
c.draw(win)
r=Rectangle(Point(20,20),Point(40,40))
r.setFill(color_rgb(0,255,150))
r.setWidth(3)
r.draw(win)
l=Line(Point(100,100),Point(100,200))
l.setOutline("red4")
l.setArrow("first")
l.draw(win)
oval=Oval(Point(50,50), Point(60,100))      
oval.draw(win)
shape=Polygon(Point(50,50),Point(100,100),Point(50,100),Point(100,50))
shape.setFill("orange")
shape.draw(win)
t=Text(Point(100,100), "Hello World!")
t.setFace("courier")
t.setSize(16)
t.setStyle("italic")
t.draw(win)
def main():
    win=GraphWin()
    shape=Circle(Point(50,50),20)
    shape.setOutline("red")
    shape.setFill("red")
    shape.draw(win)
    for i in range(10):
        p=win.getMouse()
        c=shape.getCenter()
        dx=p.getX()-c.getX()
        dy=p.getY()-c.getY()
        shape.move(dx,dy)
    win.close()
main()
def main():
    win=GraphWin()
    shape1=Circle(Point(100,100),100)
    shape1.setOutline("black")
    shape1.setFill("white")
    shape2=Circle(Point(100,100),80)
    shape2.setOutline("black")
    shape2.setFill("black")
    shape3=Circle(Point(100,100),60)
    shape3.setOutline("black")
    shape3.setFill("blue")
    shape4=Circle(Point(100,100),40)
    shape4.setOutline("black")
    shape4.setFill("red")
    shape5=Circle(Point(100,100),20)
    shape5.setOutline("black")
    shape5.setFill("yellow")
    shape1.draw(win)
    shape2.draw(win)
    shape3.draw(win)
    shape4.draw(win)
    shape5.draw(win)
main()
def main():
    win=GraphWin()
    oval1=Oval(Point(50,50), Point(75,100))
    oval1.setFill("white")
    oval2=Oval(Point(125,50), Point(150,100))
    oval2.setFill("white")
    circle=Circle(Point(100,100),90)
    circle.setFill("yellow")
    line1=Line(Point(150,150),Point(50,150))
    circle.draw(win)
    line1.draw(win)
    oval1.draw(win)
    oval2.draw(win)
main()
import math
def main():
    win=GraphWin("Line Segment Information")
    point1=win.getMouse()
    point2=win.getMouse()
    line=Line(point1,point2)
    line.draw(win)
    midpointx=(point1.getX()+point2.getX())/2
    midpointy=(point1.getY()+point2.getY())/2
    midpoint=Point(midpointx, midpointy)
    midpoint.setFill("cyan")
    midpoint.draw(win)
    dx=point2.getX()-point1.getX()
    dy=point2.getY()-point1.getY()
    slope=dy/dx
    length=math.sqrt(dx**2+dy**2)
    ltext=Text(Point(50,50),f"Length is:{length:.2f}")
    ltext.draw(win)
    stext=Text(Point(50,60),f"Slope is:{slope:.2f}")
    stext.draw(win)
    win.getMouse()
    win.close()
main()
